---
etcd:
  image: microbox/etcd
  ports:
    - "4001"
  volumes:
    - ./etcd.data:/data
  command: -name=dcron1

consul:
  image: progrium/consul
  ports:
    - "8500"
  hostname: node1
  command: -server -bootstrap -ui-dir=/ui

dkron_seed:
  links:
    - consul
  ports:
    - "8080"
  build: .
  volumes:
    - ./:/gopath/src/github.com/victorcoder/dkron
  environment:
    - GODEBUG=netdns=go
  command: go run main.go agent -server -backend=consul -backend-machine=consul:8500 -join=dkron:8946 -log-level=debug

dkron:
  links:
    - consul
    - dkron_seed
  ports:
    - "8080"
  build: .
  volumes:
    - ./:/gopath/src/github.com/victorcoder/dkron
  environment:
    - GODEBUG=netdns=go
  command: go run main.go agent -server -backend=consul -backend-machine=consul:8500 -join=dkron_seed:8946 -log-level=debug
