---
version: '2'
services:
  # Uncomment to use etcd
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - "2379"
    volumes:
      - ./etcd.data:/data
    command: etcd -name=dkron1 -advertise-client-urls http://etcd:2379,http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379

  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8300"
    hostname: node1
    command: agent -server -bootstrap -client=0.0.0.0

  # zk:
  #   image: zookeeper
  #   ports:
  #     - "2181"
  #   hostname: node1

  zoo1:
    image: zookeeper
    restart: always
    ports:
        - 2181:2181
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper
    restart: always
    ports:
        - 2182:2181
    environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper
    restart: always
    ports:
        - 2183:2181
    environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  dkron:
    build: .
    depends_on:
      - consul
      - etcd
      - zoo1
    ports:
      - "8080"
    volumes:
     - ./:/gopath/src/github.com/victorcoder/dkron
    environment:
      - GODEBUG=netdns=go
    # Uncomment to use consul
    #command: scripts/entrypoint.sh agent -server -backend=consul -backend-machine=consul:8500 -join=dkron:8946 -log-level=debug
    # Uncomment to use etcd
    command: scripts/entrypoint.sh agent -server -backend=etcd -backend-machine=etcd:2379 -join=dkron:8946 -log-level=debug
    # Uncomment to use zk
    # command: scripts/entrypoint.sh agent -server -backend=zk -backend-machine=zoo1:2181 -join=dkron:8946 -log-level=debug
