---
etcd:
  image: microbox/etcd
  ports:
    - "4001:4001"
    - "7001:7001"
  volumes:
    - ./etcd.data:/data
  command: -name=dcron1

consul:
  image: progrium/consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  hostname: node1
  command: -server -bootstrap -ui-dir=/ui

dkron:
  links:
    - consul
    - etcd
  ports:
    - "8080:8080"
    - "8946:8946"
  build: .
  volumes:
    - /Users/victorcoder/src/github.com/victorcoder/dkron:/gopath/src/github.com/victorcoder/dkron
  command: go run main.go agent -server -backend=etcd -backend-machine=etcd:4001
