---
site_name: Dkron - Distributed cron
theme: yeti
theme_dir: 'dkron_theme'
extra_css: ["css/app.css"]
extra_javascript: ["js/app.js"]
site_url: http://dkron.io
repo_url: https://github.com/victorcoder/dkron
site_author: Victor Castell
copyright: © 2015 Victor Castell - victor@victorcastell.com
google_analytics: ['UA-571371-14', 'dcron.io']
pages:
  - Home: 'index.md'
  - Intro: 'intro.md'
  - Docs:
    - 'docs/getting-started.md'
    - 'docs/configuration.md'
    - 'docs/api.md'
  - About:
    - 'about/dkron_vs_other_software.md'
    - 'about/license.md'
