---
site_name: Dcron - Distributed cron
theme: flatly
site_url: dcron.io
repo_url: https://github.com/victorcoder/dcron
site_author: Victor Castell
copyright: Victor Castell, www.victorcastell.com
google_analytics: ['', 'dcron.io']
# pages:
#   - Home: 'index.md'
#   - Intro: 'intro.md'
