---
site_name: Dcron - Distributed cron
theme: yeti
theme_dir: 'dcron_theme'
extra_css: ["css/app.css"]
extra_javascript: ["js/app.js"]
site_url: http://dcron.io
repo_url: https://github.com/victorcoder/dcron
site_author: Victor Castell
copyright: © 2015 Victor Castell - victor@victorcastell.com
google_analytics: ['UA-571371-14', 'dcron.io']
# pages:
#   - Home: 'index.md'
#   - Intro: 'intro.md'
